# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oetiqueter_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OEtiqueter(object):
    def setupUi(self, OEtiqueter):
        OEtiqueter.setObjectName("OEtiqueter")
        OEtiqueter.resize(1024, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OEtiqueter.sizePolicy().hasHeightForWidth())
        OEtiqueter.setSizePolicy(sizePolicy)
        OEtiqueter.setMinimumSize(QtCore.QSize(1024, 600))
        OEtiqueter.setMaximumSize(QtCore.QSize(1042, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logoieo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OEtiqueter.setWindowIcon(icon)
        self.surveyLabel = QtWidgets.QLabel(OEtiqueter)
        self.surveyLabel.setGeometry(QtCore.QRect(6, 6, 1024, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surveyLabel.sizePolicy().hasHeightForWidth())
        self.surveyLabel.setSizePolicy(sizePolicy)
        self.surveyLabel.setMinimumSize(QtCore.QSize(1024, 25))
        self.surveyLabel.setMaximumSize(QtCore.QSize(1024, 25))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.surveyLabel.setFont(font)
        self.surveyLabel.setStyleSheet("")
        self.surveyLabel.setTextFormat(QtCore.Qt.AutoText)
        self.surveyLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.surveyLabel.setObjectName("surveyLabel")
        self.tableWidget = QtWidgets.QTableWidget(OEtiqueter)
        self.tableWidget.setGeometry(QtCore.QRect(6, 71, 910, 455))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(910, 455))
        self.tableWidget.setMaximumSize(QtCore.QSize(910, 455))
        self.tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(OEtiqueter)
        self.layoutWidget.setGeometry(QtCore.QRect(936, 37, 82, 465))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bottlesLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottlesLabel.sizePolicy().hasHeightForWidth())
        self.bottlesLabel.setSizePolicy(sizePolicy)
        self.bottlesLabel.setMinimumSize(QtCore.QSize(80, 60))
        self.bottlesLabel.setMaximumSize(QtCore.QSize(90, 60))
        self.bottlesLabel.setScaledContents(False)
        self.bottlesLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.bottlesLabel.setObjectName("bottlesLabel")
        self.verticalLayout.addWidget(self.bottlesLabel)
        self.bottle01 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle01.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle01.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle01.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle01.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle01.setObjectName("bottle01")
        self.buttonGroup = QtWidgets.QButtonGroup(OEtiqueter)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.setExclusive(False)
        self.buttonGroup.addButton(self.bottle01)
        self.verticalLayout.addWidget(self.bottle01)
        self.bottle02 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle02.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle02.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle02.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle02.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle02.setObjectName("bottle02")
        self.buttonGroup.addButton(self.bottle02)
        self.verticalLayout.addWidget(self.bottle02)
        self.bottle03 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle03.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle03.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle03.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle03.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle03.setObjectName("bottle03")
        self.buttonGroup.addButton(self.bottle03)
        self.verticalLayout.addWidget(self.bottle03)
        self.bottle04 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle04.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle04.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle04.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle04.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle04.setObjectName("bottle04")
        self.buttonGroup.addButton(self.bottle04)
        self.verticalLayout.addWidget(self.bottle04)
        self.bottle05 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle05.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle05.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle05.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle05.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle05.setObjectName("bottle05")
        self.buttonGroup.addButton(self.bottle05)
        self.verticalLayout.addWidget(self.bottle05)
        self.bottle06 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle06.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle06.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle06.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle06.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle06.setObjectName("bottle06")
        self.buttonGroup.addButton(self.bottle06)
        self.verticalLayout.addWidget(self.bottle06)
        self.bottle07 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle07.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle07.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle07.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle07.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle07.setObjectName("bottle07")
        self.buttonGroup.addButton(self.bottle07)
        self.verticalLayout.addWidget(self.bottle07)
        self.bottle08 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle08.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle08.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle08.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle08.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle08.setObjectName("bottle08")
        self.buttonGroup.addButton(self.bottle08)
        self.verticalLayout.addWidget(self.bottle08)
        self.bottle09 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle09.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle09.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle09.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle09.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle09.setObjectName("bottle09")
        self.buttonGroup.addButton(self.bottle09)
        self.verticalLayout.addWidget(self.bottle09)
        self.bottle10 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle10.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle10.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle10.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle10.setObjectName("bottle10")
        self.buttonGroup.addButton(self.bottle10)
        self.verticalLayout.addWidget(self.bottle10)
        self.bottle11 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle11.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle11.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle11.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle11.setObjectName("bottle11")
        self.buttonGroup.addButton(self.bottle11)
        self.verticalLayout.addWidget(self.bottle11)
        self.bottle12 = QtWidgets.QPushButton(self.layoutWidget)
        self.bottle12.setMinimumSize(QtCore.QSize(80, 25))
        self.bottle12.setMaximumSize(QtCore.QSize(80, 25))
        self.bottle12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bottle12.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bottle12.setObjectName("bottle12")
        self.buttonGroup.addButton(self.bottle12)
        self.verticalLayout.addWidget(self.bottle12)
        self.noBottle = QtWidgets.QPushButton(self.layoutWidget)
        self.noBottle.setMinimumSize(QtCore.QSize(80, 25))
        self.noBottle.setMaximumSize(QtCore.QSize(80, 25))
        self.noBottle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.noBottle.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.noBottle.setObjectName("noBottle")
        self.buttonGroup.addButton(self.noBottle)
        self.verticalLayout.addWidget(self.noBottle)
        self.splitter = QtWidgets.QSplitter(OEtiqueter)
        self.splitter.setGeometry(QtCore.QRect(6, 38, 300, 25))
        self.splitter.setMinimumSize(QtCore.QSize(300, 0))
        self.splitter.setMaximumSize(QtCore.QSize(303, 25))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.stationLabel = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stationLabel.sizePolicy().hasHeightForWidth())
        self.stationLabel.setSizePolicy(sizePolicy)
        self.stationLabel.setMinimumSize(QtCore.QSize(60, 25))
        self.stationLabel.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stationLabel.setFont(font)
        self.stationLabel.setObjectName("stationLabel")
        self.stationCombo = QtWidgets.QComboBox(self.splitter)
        self.stationCombo.setMinimumSize(QtCore.QSize(100, 25))
        self.stationCombo.setMaximumSize(QtCore.QSize(100, 25))
        self.stationCombo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stationCombo.setObjectName("stationCombo")
        self.castLabel = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.castLabel.sizePolicy().hasHeightForWidth())
        self.castLabel.setSizePolicy(sizePolicy)
        self.castLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.castLabel.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.castLabel.setFont(font)
        self.castLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.castLabel.setObjectName("castLabel")
        self.castText = QtWidgets.QLineEdit(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.castText.sizePolicy().hasHeightForWidth())
        self.castText.setSizePolicy(sizePolicy)
        self.castText.setMinimumSize(QtCore.QSize(50, 25))
        self.castText.setMaximumSize(QtCore.QSize(60, 25))
        self.castText.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.castText.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.castText.setMaxLength(3)
        self.castText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.castText.setObjectName("castText")
        self.layoutWidget1 = QtWidgets.QWidget(OEtiqueter)
        self.layoutWidget1.setGeometry(QtCore.QRect(6, 535, 268, 58))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.addDepthButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.addDepthButton.setMinimumSize(QtCore.QSize(130, 25))
        self.addDepthButton.setMaximumSize(QtCore.QSize(130, 25))
        self.addDepthButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addDepthButton.setIcon(icon1)
        self.addDepthButton.setObjectName("addDepthButton")
        self.gridLayout.addWidget(self.addDepthButton, 0, 0, 1, 1)
        self.removeDepthButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeDepthButton.sizePolicy().hasHeightForWidth())
        self.removeDepthButton.setSizePolicy(sizePolicy)
        self.removeDepthButton.setMinimumSize(QtCore.QSize(130, 25))
        self.removeDepthButton.setMaximumSize(QtCore.QSize(130, 25))
        self.removeDepthButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeDepthButton.setIcon(icon2)
        self.removeDepthButton.setObjectName("removeDepthButton")
        self.gridLayout.addWidget(self.removeDepthButton, 0, 1, 1, 1)
        self.printButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printButton.sizePolicy().hasHeightForWidth())
        self.printButton.setSizePolicy(sizePolicy)
        self.printButton.setMinimumSize(QtCore.QSize(130, 25))
        self.printButton.setMaximumSize(QtCore.QSize(130, 25))
        self.printButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printButton.setIcon(icon3)
        self.printButton.setObjectName("printButton")
        self.gridLayout.addWidget(self.printButton, 1, 0, 1, 1)
        self.aboutButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutButton.sizePolicy().hasHeightForWidth())
        self.aboutButton.setSizePolicy(sizePolicy)
        self.aboutButton.setMinimumSize(QtCore.QSize(130, 25))
        self.aboutButton.setMaximumSize(QtCore.QSize(130, 25))
        self.aboutButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.aboutButton.setObjectName("aboutButton")
        self.gridLayout.addWidget(self.aboutButton, 1, 1, 1, 1)
        self.stationLabel.setBuddy(self.stationCombo)
        self.castLabel.setBuddy(self.castText)

        self.retranslateUi(OEtiqueter)
        self.castText.editingFinished.connect(self.tableWidget.setFocus)
        QtCore.QMetaObject.connectSlotsByName(OEtiqueter)
        OEtiqueter.setTabOrder(self.stationCombo, self.castText)
        OEtiqueter.setTabOrder(self.castText, self.bottle02)
        OEtiqueter.setTabOrder(self.bottle02, self.bottle03)
        OEtiqueter.setTabOrder(self.bottle03, self.bottle04)
        OEtiqueter.setTabOrder(self.bottle04, self.bottle05)
        OEtiqueter.setTabOrder(self.bottle05, self.bottle06)
        OEtiqueter.setTabOrder(self.bottle06, self.bottle09)
        OEtiqueter.setTabOrder(self.bottle09, self.bottle10)
        OEtiqueter.setTabOrder(self.bottle10, self.printButton)
        OEtiqueter.setTabOrder(self.printButton, self.bottle11)
        OEtiqueter.setTabOrder(self.bottle11, self.bottle08)
        OEtiqueter.setTabOrder(self.bottle08, self.bottle07)
        OEtiqueter.setTabOrder(self.bottle07, self.bottle12)
        OEtiqueter.setTabOrder(self.bottle12, self.addDepthButton)
        OEtiqueter.setTabOrder(self.addDepthButton, self.removeDepthButton)
        OEtiqueter.setTabOrder(self.removeDepthButton, self.tableWidget)
        OEtiqueter.setTabOrder(self.tableWidget, self.bottle01)

    def retranslateUi(self, OEtiqueter):
        _translate = QtCore.QCoreApplication.translate
        OEtiqueter.setWindowTitle(_translate("OEtiqueter", "O_Etiqueter: Hidrography sample labeller"))
        self.surveyLabel.setText(_translate("OEtiqueter", "Survey"))
        self.bottlesLabel.setText(_translate("OEtiqueter", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Bottle</span></p><p align=\"center\">(F1-F12)</p></body></html>"))
        self.bottle01.setText(_translate("OEtiqueter", "1"))
        self.bottle01.setShortcut(_translate("OEtiqueter", "F1"))
        self.bottle02.setText(_translate("OEtiqueter", "2"))
        self.bottle02.setShortcut(_translate("OEtiqueter", "F2"))
        self.bottle03.setText(_translate("OEtiqueter", "3"))
        self.bottle03.setShortcut(_translate("OEtiqueter", "F3"))
        self.bottle04.setText(_translate("OEtiqueter", "4"))
        self.bottle04.setShortcut(_translate("OEtiqueter", "F4"))
        self.bottle05.setText(_translate("OEtiqueter", "5"))
        self.bottle05.setShortcut(_translate("OEtiqueter", "F5"))
        self.bottle06.setText(_translate("OEtiqueter", "6"))
        self.bottle06.setShortcut(_translate("OEtiqueter", "F6"))
        self.bottle07.setText(_translate("OEtiqueter", "7"))
        self.bottle07.setShortcut(_translate("OEtiqueter", "F7"))
        self.bottle08.setText(_translate("OEtiqueter", "8"))
        self.bottle08.setShortcut(_translate("OEtiqueter", "F8"))
        self.bottle09.setText(_translate("OEtiqueter", "9"))
        self.bottle09.setShortcut(_translate("OEtiqueter", "F9"))
        self.bottle10.setText(_translate("OEtiqueter", "10"))
        self.bottle10.setShortcut(_translate("OEtiqueter", "F10"))
        self.bottle11.setText(_translate("OEtiqueter", "11"))
        self.bottle11.setShortcut(_translate("OEtiqueter", "F11"))
        self.bottle12.setText(_translate("OEtiqueter", "12"))
        self.bottle12.setShortcut(_translate("OEtiqueter", "F12"))
        self.noBottle.setText(_translate("OEtiqueter", "NO"))
        self.noBottle.setShortcut(_translate("OEtiqueter", "Del"))
        self.stationLabel.setText(_translate("OEtiqueter", "Station:"))
        self.castLabel.setText(_translate("OEtiqueter", "Cast:   "))
        self.castText.setText(_translate("OEtiqueter", "000"))
        self.addDepthButton.setText(_translate("OEtiqueter", "Add depth"))
        self.removeDepthButton.setText(_translate("OEtiqueter", "Remove depth"))
        self.printButton.setText(_translate("OEtiqueter", "Print!"))
        self.aboutButton.setText(_translate("OEtiqueter", "About..."))
import resources_rc
